### ISSUE TITLE
[WebApp] User Registration inside dashboard !

### ISSUE THREAD

**Issue by Tarun747** [slydogshah/appGalCloud#22]
Recommended using private routes in REAT to keep the dashboard component private to logged-in users only. Keeping registration as a child component of Authentication instead of Dashboard.

Find more about private routes - https://medium.com/@thanhbinh.tran93/private-route-public-route-and-restricted-route-with-react-router-d50b27c15f5e

Usage of JWT (JSON Web Token) for user session during logged-in users for the dashboard.

Find more about JWT here -https://jwt.io/
 

![Screenshot 2021-02-17 at 10 39 57 PM](https://user-images.githubusercontent.com/39861004/108241012-65e9db00-7171-11eb-8fe4-f3302c0a036e.png)

**Comment by Tarun747** [comment]
Registration Component is a part of LogIn switching in between registration and login improves user experience.
https://user-images.githubusercontent.com/39861004/109341435-70eaec80-7890-11eb-87c7-6bfb08ace08e.mov

**Comment by Tarun747** [comment]
@slydogshah Recommended using private routes in REAT to keep the dashboard component private to logged-in users only. Keeping registration as a child component of Authentication instead of Dashboard.

@slydogshah [Action Item]: 

> Implementing [JWT](https://jwt.io/) on API responses with user sessions. 

Usage of JWT (JSON Web Token) for user session during logged-in users for the dashboard.

Find more about JWT here -https://jwt.io/

**Comment by slydogshah** [comment]
looks good
