### ISSUE TITLE
[Mobile App] Flutter Mobile App Gradle issue !

### ISSUE THREAD

**Issue by Tarun747** [slydogshah/appGalCloud#29]
https://github.com/flutter/flutter/issues/55619

![WhatsApp Image 2021-02-18 at 1 48 48 PM](https://user-images.githubusercontent.com/39861004/108551732-58ba2100-7316-11eb-8c90-712887bde04d.jpeg)

**Comment by JaiAravindh-git** [comment]
Assign

**Comment by slydogshah** [comment]
Done
