### ISSUE TITLE
Dashboard Theme

### ISSUE THREAD

**Issue by slydogshah** [slydogshah/appGalCloud#31]
Based on the agreed theme

All pages

**Comment by Tarun747** [comment]
Please share which theme you are referring to.

**Comment by bugsbunnyshah** [comment]
I am looking for the Dashboard with this theme

http://staging.wesourceu.com/

**Comment by bugsbunnyshah** [comment]
Not this.

**Comment by bugsbunnyshah** [comment]
Example of why your commits are causing a major setback.

Compare the latest Home.js on branch ironman to Home.js on branch ux

A bunch of important code was just removed. Why?

If I have to guess, turning a fully integrated page into a static page?

That is not the goal here to launch a static site

Thanks

**Comment by slydogshah** [comment]
Done
