### ISSUE TITLE
RegistrationPage: Restore the original fields

### ISSUE THREAD

**Issue by slydogshah** [slydogshah/appGalCloud#32]

**Comment by Tarun747** [comment]
**Previous Feilds in Registration**

FYI previous fields `input` element being used along with API 

> 

`axios
              .post("http://localhost:8080/registration/org/", {
                email: this.state.email,
                password: this.state.password,
                mobile: this.state.mobile,
                sourceOrgId: this.state.sourceOrgId,
                profileType: this.state.profileType,
              })
              .then((res) => {
                debugger
                console.log(res)
                message.success('Logging In..')
              })
              .catch((err) => {
                console.log(err)
                message.error('Error in Registration !!')
              })` 





we used exact same API POST method for registration please updated body in case there are changes made from backend for registration.


> 
![Screenshot 2021-03-03 at 12 09 20 AM](https://user-images.githubusercontent.com/39861004/109699465-9ccee080-7bb6-11eb-9ded-7556d35340b4.png)

> 
![Screenshot 2021-03-03 at 12 24 43 AM](https://user-images.githubusercontent.com/39861004/109699714-e6b7c680-7bb6-11eb-8ae7-e277290cca84.png)

**Comment by bugsbunnyshah** [comment]
This is the original

https://github.com/slydogshah/appGalCloud/blob/ironman/appgal-cloud/bugs/registration.png

**Comment by bugsbunnyshah** [comment]
Notice they are not aligned

Thanks

**Comment by slydogshah** [comment]
Done
